# Generated by Django 6.0.1 on 2026-01-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
